export const FACTORY_ABI = [
  {
    name: "getAllMarkets",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address[]" }],
  },
  {
    name: "getMarkets",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "offset", type: "uint256" },
      { name: "limit", type: "uint256" },
    ],
    outputs: [{ name: "result", type: "address[]" }],
  },
  {
    name: "getMarketCount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "isAssetWhitelisted",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "string" }],
    outputs: [{ type: "bool" }],
  },
  {
    name: "getWhitelistedAssets",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "string[]" }],
  },
  {
    name: "minCreatorDeposit",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "collateralToken",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "assetFeeds",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "asset", type: "string" }],
    outputs: [{ type: "address" }],
  },
  {
    name: "createMarket",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "asset", type: "string" },
      { name: "bandPercent", type: "uint256" },
      { name: "duration", type: "uint256" },
      { name: "creatorSide", type: "bool" },
      { name: "creatorAmount", type: "uint256" },
      { name: "boundTokenName", type: "string" },
      { name: "boundTokenSymbol", type: "string" },
      { name: "breakTokenName", type: "string" },
      { name: "breakTokenSymbol", type: "string" },
    ],
    outputs: [
      { name: "market", type: "address" },
      { name: "boundToken", type: "address" },
      { name: "breakToken", type: "address" },
    ],
  },
] as const;

export const ERC20_ABI = [
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }],
    outputs: [{ type: "bool" }],
  },
  {
    name: "allowance",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "balanceOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const CHAINLINK_ABI = [
  {
    name: "latestRoundData",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "roundId", type: "uint80" },
      { name: "answer", type: "int256" },
      { name: "startedAt", type: "uint256" },
      { name: "updatedAt", type: "uint256" },
      { name: "answeredInRound", type: "uint80" },
    ],
  },
  {
    name: "decimals",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }],
  },
] as const;

export const MARKET_ABI = [
  {
    name: "marketConfig",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "asset", type: "string" },
      { name: "lowerBound", type: "uint256" },
      { name: "upperBound", type: "uint256" },
      { name: "expiryTimestamp", type: "uint256" },
      { name: "creationTimestamp", type: "uint256" },
      { name: "startPrice", type: "uint256" },
      { name: "initialized", type: "bool" },
    ],
  },
  {
    name: "status",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint8" }], // 0=PENDING,1=LIVE,2=SETTLED,3=CANCELLED
  },
  {
    name: "boundPool",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "breakPool",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "creatorSide",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    name: "creator",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "boundWins",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "bool" }],
  },
  {
    name: "resolvedPrice",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "previewYield",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "getBoundPrice",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "getBreakPrice",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "getEstimatedPayout",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "isBound", type: "bool" },
      { name: "usdcAmount", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "positions",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [
      { name: "principal",    type: "uint256" },
      { name: "morphoShares", type: "uint256" },
      { name: "isBound",      type: "bool" },
      { name: "exists",       type: "bool" },
      { name: "claimed",      type: "bool" },
    ],
  },
  {
    name: "redemptionRate",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    name: "boundToken",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "breakToken",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    name: "redeemWinner",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "tokenAmount", type: "uint256" }],
    outputs: [],
  },
  {
    name: "claimLoserYield",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    name: "joinBound",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }, { name: "minTokensOut", type: "uint256" }],
    outputs: [],
  },
  {
    name: "joinBreak",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }, { name: "minTokensOut", type: "uint256" }],
    outputs: [],
  },
] as const;
